# Generated by Django 5.1 on 2024-11-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('departamento', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('link_download', models.URLField(blank=True)),
                ('arquivo', models.FileField(blank=True, upload_to='manuais/')),
                ('departamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('link_download', models.URLField(blank=True)),
                ('arquivo', models.FileField(blank=True, upload_to='programas/')),
                ('departamento', models.CharField(max_length=255)),
            ],
        ),
    ]
