# Generated by Django 5.1 on 2024-11-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_link_icone_manual_icone_programa_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='icone',
        ),
    ]
