# Generated by Django 5.1 on 2024-11-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_link_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='departamento',
            field=models.CharField(choices=[('TI', 'TI'), ('RH', 'RH'), ('SSO', 'SS0'), ('FISCAL', 'FISCAL'), ('LOGISTICA', 'LOGISTICA'), ('GENERICO', 'GENERICO')], max_length=255),
        ),
        migrations.AlterField(
            model_name='manual',
            name='departamento',
            field=models.CharField(choices=[('TI', 'TI'), ('RH', 'RH'), ('SSO', 'SS0'), ('FISCAL', 'FISCAL'), ('LOGISTICA', 'LOGISTICA'), ('GENERICO', 'GENERICO')], max_length=255),
        ),
        migrations.AlterField(
            model_name='programa',
            name='departamento',
            field=models.CharField(choices=[('TI', 'TI'), ('RH', 'RH'), ('SSO', 'SS0'), ('FISCAL', 'FISCAL'), ('LOGISTICA', 'LOGISTICA'), ('GENERICO', 'GENERICO')], max_length=255),
        ),
    ]
