# Generated by Django 5.1 on 2024-11-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_link_departamento_alter_manual_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='departamento',
            field=models.CharField(choices=[('TI', 'TI'), ('RH', 'RH'), ('SSO', 'SSo'), ('FISCAL', 'FISCAL'), ('LOGISTICA', 'LOGISTICA'), ('GENERICO', 'GENERICO')], max_length=255),
        ),
    ]
