# Generated by Django 5.1 on 2024-11-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_programa_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='departamento',
            field=models.CharField(choices=[('GENERICO', 'GENERICO'), ('TI', 'TI'), ('RH', 'RH'), ('SSO', 'SSo'), ('FISCAL', 'FISCAL'), ('LOGISTICA', 'LOGISTICA')], max_length=255),
        ),
    ]
