# Generated by Django 5.1 on 2024-11-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_programa_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='departamento',
            field=models.CharField(choices=[('TI', 'TI'), ('RH', 'RH'), ('SSO', 'SS0'), ('FISCAL', 'FISCAL'), ('LOGISTICA', 'LOGISTICA'), ('GERAL', 'GERAL')], max_length=255),
        ),
        migrations.AlterField(
            model_name='manual',
            name='departamento',
            field=models.CharField(choices=[('GERAL', 'GERAL'), ('TI', 'TI'), ('RH', 'RH'), ('SSO', 'SS0'), ('FISCAL', 'FISCAL'), ('LOGISTICA', 'LOGISTICA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='programa',
            name='departamento',
            field=models.CharField(choices=[('LOGISTICA', 'LOGISTICA'), ('GERAL', 'GERAL'), ('TI', 'TI'), ('RH', 'RH'), ('SSO', 'SSo'), ('FISCAL', 'FISCAL')], max_length=255),
        ),
    ]
