# Generated by Django 5.1 on 2024-11-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_link_departamento_alter_manual_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='departamento',
            field=models.CharField(choices=[('TI', 'TI'), ('RH', 'RH'), ('SSO', 'SS0'), ('FISCAL', 'FISCAL'), ('LOGISTICA', 'LOGISTICA'), ('GERAL', 'GERAL'), ('OUTROS', 'OUTROS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='manual',
            name='departamento',
            field=models.CharField(choices=[('GERAL', 'GERAL'), ('TI', 'TI'), ('RH', 'RH'), ('SSO', 'SS0'), ('FISCAL', 'FISCAL'), ('LOGISTICA', 'LOGISTICA'), ('OUTROS', 'OUTROS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='programa',
            name='departamento',
            field=models.CharField(choices=[('LOGISTICA', 'LOGISTICA'), ('GERAL', 'GERAL'), ('TI', 'TI'), ('RH', 'RH'), ('SSO', 'SSo'), ('FISCAL', 'FISCAL'), ('OUTROS', 'OUTROS')], max_length=255),
        ),
    ]
